modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/dragon-forge/SolarFluxReborn/issues"
license="All rights reserved"

[[mods]]
modId="solarflux"
version="${file.jarVersion}"
displayName="Solar Flux Reborn"
updateJSONURL="https://api.modrinth.com/updates/4QG5lev4/forge_updates.json"
displayURL="https://modrinth.com/mod/4QG5lev4"
# logoFile="assets/solarflux/textures/logo.png" #optional
credits="Nauktis for original Solar Flux for 1.7"
authors="Zeitheron"

description='''
Solar Flux Reborn is aimed at implementing easy-to-use solar panels and providing modpack devs the ability to create their own panels with ease!
'''

[[dependencies.solarflux]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.solarflux]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.solarflux]]
    modId = "hammerlib"
    mandatory = true
    versionRange = "[16.5.50,)"
    ordering = "NONE"
    side = "BOTH"
